// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/50387d40462301d54cda62e24d3b2ee46540f24a/gulp-mocha/index.d.ts
declare module 'gulp-mocha' {
// Type definitions for gulp-mocha
// Project: https://github.com/sindresorhus/gulp-mocha
// Definitions by: Asana <https://asana.com>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

/// <reference types="mocha"/>
/// <reference types="node"/>


function mocha(setupOptions?: MochaSetupOptions): NodeJS.ReadWriteStream;
namespace mocha { }
export = mocha;
}
